FROM node:18.20-alpine AS compile-image

WORKDIR /opt/ng
COPY package.json /opt/ng/package.json
RUN npm install --force
RUN npm install -g @angular/cli
ENV PATH="./node_modules/.bin:$PATH"
COPY . ./
RUN ng build --configuration production --base-href /lifehood-backend/
RUN npm cache clean --force
RUN rm -rf /root/.npm
RUN rm -rf node_modules

EXPOSE 8080
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=compile-image /opt/ng/dist/lifehood-backend/browser /usr/share/nginx/html
